# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: 
  name: Default
  #vmImage: ubuntu-latest

steps:

- task: DownloadSecureFile@1
  name: settingsxml
  inputs:
    secureFile: 'settings.xml'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      New-Item -Type Directory -Force "${HOME}/.m2"
      Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/settings.xml"
     
# - task: Maven@3
#   inputs:
#     displayName: maven clean install
#     mavenPomFile: '$(system.defaultWorkingDirectory)/cicd-pipeline-demo/pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'deploy -e'


- task: Maven@3
  inputs:
    displayName: maven deploy 
    mavenPomFile: '$(system.defaultWorkingDirectory)/cicd-pipeline-demo/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'clean deploy -Dusername=muzzumiljaved-systems -Dpassword=Muzzumil@038712 -Denvironment=DEV -Dregion=us-east-2 -Dworkers=1 -DworkerType=MICRO -Dmule.version=4.4.0 -Dapplication.name=demp-application -DmuleDeploy'




